# crypto-config.yaml

OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  # Ospedali
  - Name: HospitalA
    Domain: hospitala.example.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: HospitalB
    Domain: hospitalb.example.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  # Laboratori di Analisi
  - Name: Lab
    Domain: lab.example.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  # Farmacie
  - Name: Pharmacy
    Domain: pharmacy.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  # Medici Privati
  - Name: Doctors
    Domain: doctors.example.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 2
