name: CI for Hyperledger Fabric Chaincode

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20.0"
      - name: Install dependencies
        run: |
          cd chaincodes/chaincodes_go
          for d in */ ; do
            if [ -d "$d" ]; then
              cd "$d"
              go mod tidy
              go mod download
              cd ..
            fi
          done
      - name: Run tests in all chaincode modules
        run: |
          cd chaincodes/chaincodes_go
          for d in */ ; do
            if [ -d "$d" ]; then
              echo "Testing in $d"
              cd "$d"
              go test -list=.
              cd ..
            fi
          done
