name: CI for Hyperledger Fabric Chaincode

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21.0'
    - name: Install dependencies
      run: |
        go mod tidy
        go mod download
    - name: Run tests
      run: go test ./...
